### ISSUE TITLE
NullValueInspector avoids custom converter for boolean

### ISSUE THREAD

**Issue by HerrDerb** [BAData/protobuf-converter#11]
I convert a Java boolean to a integer for protobuf, as this is more efficient as a String. 
For this I've created a custom `TypeConverter` which converts a int to the enum and otherwise.
One enum has the value `0`. This causes the `DomainWriter` to use the `DefaultValueConverter` ending in not converting the enum back correctly.

If the protobuf field holds `0` it will not use my `EnumIntConverter` to convert back to my enum

    @Override
	protected void write(final Object destination, final FieldResolver fieldResolver, final Object value) throws WriteException {
		NullValueInspector nullInspector = fieldResolver.getNullValueInspector();
		DefaultValue defaultValueCreator = fieldResolver.getDefaultValue();
		TypeConverter<?, ?> typeConverter = fieldResolver.getTypeConverter();
		if (nullInspector.isNull(value)) {
			writeValue(destination, fieldResolver, defaultValueCreator.generateValue(fieldResolver.getDomainType()));
		} else {
			writeValue(destination, fieldResolver, typeConverter.toDomainValue(value));
		}
	}

**Comment by HerrDerb** [comment]
In the mean time I figured that you can set your own `NullInspector`. What I still don't understand: What is the purpose of the `DefaultNullInspector`? To me it only seems disturbing.

**Comment by jsjem** [comment]
When you receives a protobuf message it always transforms into Protobuf Java Object with all fields initialized. And in some cases you need to know if a field  have existed in the protobuf message or it have been initialized by default value during the time of convertion from protobuf message to Protobuf Java Object.
Example:
**Protobuf message**
```
message User {
	int64 id = 1;
	string name = 2;
	string password = 3;
}
```
**Protobuf Java Object**
```
public class UserProto {
	public  static final class User extends com.google.protobuf.GeneratedMessage implements User
		public long id; //int64 type in protobuf message always transforms into primitive long Java type. 
				//By default long fields initialize with 0 value.
		public String name;
		public String password;
		...
	}
	...
}
```
**Domain Model Object**
```
public class User {
	@ProtoField(name = "id")
	public Long userId;  //By default Long fields initialize with null value.
	@ProtoField
	public String name;
	@ProtoField
	public String password;
	...
}
```
Suppose you want to create a new user record in the database when field `userId` of your domain model object (**User**) is **null**. And edit user record in case when `userId != null`. Now you have a problem: when client sends you protobuf message with `id=0` or `id` does not exists in the message, instance of **UserProto.User** always has `id` initialized with `0` value, and when you convert **UserProto.User** to domain model object **User** you will get `userId = 0`. **DefaultNullInspector** is necessary to avoid such issues. But it adds some restrictions to possible field values, e.g.: you can't apply values that Java uses as defaults for initializing fields.

**Comment by ppoffice** [comment]
@HerrDerb You may want to check this

https://github.com/ppoffice/protobuf-lite-converter/commit/2026156f6e004c3e5a5a36b2bc5f236af1f451b2

https://github.com/ppoffice/protobuf-lite-converter/commit/293e0c967cbf0f5a4ccfd1e456d625c47f45730e
