### ISSUE TITLE
Please consider looser license

### ISSUE THREAD

**Issue by jd3nn1s** [BAData/protobuf-converter#12]
Would you consider re-licensing under BSD or MIT to allow use in commercial software? Thanks.

**Comment by ghost** [comment]
We will consider changing the license of protobuf-converter to MIT.

**Comment by rasmuslund** [comment]
The GPL license is also keeping us from even looking at the project - instead we have started writing our own mapping library (which is kind of stupid)...

**Comment by jd3nn1s** [comment]
MIT would be great for us - when do you think you would decide by? We are at a decision point right now.

**Comment by ghost** [comment]
We decided switch to the MIT license.

**Comment by ghost** [comment]
Just made changes to the license - b7b3e65c1bda48a2c8ad92d14749732a035cefa9.
