### ISSUE TITLE
The method name of boolean data type

### ISSUE THREAD

**Issue by maobulang** [BAData/protobuf-converter#2]
The get method name of boolean data type must have 'is' prefix, why not use 'get' prefix?
could you tell me the reason?

**Comment by jsjem** [comment]
getters with 'is' prefix is used for **boolean** fields with primitive types. For **Boolean**  fields with reference types getters has to be with 'get' prefix. This getter naming convention is suggested for boolean properties in [JavaBeans specification](http://download.oracle.com/otndocs/jcp/7224-javabeans-1.01-fr-spec-oth-JSpec/)
