### ISSUE TITLE
convert  list field failure

### ISSUE THREAD

**Issue by maobulang** [BAData/protobuf-converter#3]
i have review the unit test, when i convert MultiMappingOwner to MultiMappingTest and the multiMappingListValue field is null , the convert will failure.
i have check the source code, the createProtobufValueList method of  the Converter class report the 
error, when the domainCollection parameter is null, the following code report the error: 
 domainCollection.getClass() 

could you help to fix the issue? or we have another way to avoid the error?

**Comment by jsjem** [comment]
It is a bug.
For now, you must initialize collection fields of your domain objects as an empty collection.

**Comment by jsjem** [comment]
fixed
